# Generated by Django 5.2.6 on 2025-09-17 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Polyuria', models.CharField(max_length=10)),
                ('Polydipsia', models.CharField(max_length=10)),
                ('sudden_weight_loss', models.CharField(max_length=10)),
                ('weakness', models.CharField(max_length=10)),
                ('Polyphagia', models.CharField(max_length=10)),
                ('Genital_thrush', models.CharField(max_length=10)),
                ('visual_blurring', models.CharField(max_length=10)),
                ('Itching', models.CharField(max_length=10)),
                ('Irritability', models.CharField(max_length=10)),
                ('delayed_healing', models.CharField(max_length=10)),
                ('partial_paresis', models.CharField(max_length=10)),
                ('muscle_stiffness', models.CharField(max_length=10)),
                ('Alopecia', models.CharField(max_length=10)),
                ('Obesity', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
