# Generated by Django 5.2.6 on 2025-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_symptoms_prediction_alter_symptoms_risk_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='BloodPressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='DiabetesPedigreeFunction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='Glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='Insulin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='Pregnancies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='SkinThickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='Alopecia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='Genital_thrush',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='Irritability',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='Itching',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='Obesity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='Polydipsia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='Polyphagia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='Polyuria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='delayed_healing',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='muscle_stiffness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='partial_paresis',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='sudden_weight_loss',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='visual_blurring',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='weakness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
